services:
  app:
    image: notes-app
    ports:
      - 127.0.0.1:3000:3000
    environment:
      - MYSQL_HOST
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DB
    volumes:
      - "./:/app"
      - node_modules:/app/node_modules
    depends_on:
      mysql:
        condition: service_healthy
  
  mysql:
    image: mysql:8.0
    environment: 
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    volumes:
      - note-mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
  
  keycloak:
    image: quay.io/keycloak/keycloak
    ports: 
      - 127.0.0.1:8080:8080
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME
      - KC_BOOTSTRAP_ADMIN_PASSWORD
    command: start-dev
    volumes:
      - keycloak-data:/opt/key-cloak/data


volumes:
  note-mysql-data:
  node_modules:
  keycloak-data:
